POST http://20.89.131.34:443/api/v1/account/sign_up
Content-Type: application/json

{
    "username": "1234",
    "mail": "jack2563@gmail.com",
    "password": "735434cae08df8e591c1549da88c6d87",
    "section": "001"
}
###
POST http://20.89.131.34:443/api/v1/account/login
Content-Type: application/json

{
    "username": "123",
    "password": "735434cae08df8e591c1549da88c6d87"
}

###
POST http://20.89.131.34/api/v1/account/delete_user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY4OTY5NDAxMSwiZXhwIjoxNjg5NzAzMDExfQ.z-d00RJZ71cjRE4he4AzJW9Ohv1n5gQvhEzbMyvdhqc

### 
POST http://20.89.131.34:443/api/v1/account/remove_user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MTY4NDkxNSwiZXhwIjoxNjkxNjkzOTE1fQ.DpDeNDLiFp6t1k1pH44BjGkj-7eHQpL_0bCO-Z5O0MA

{
    "username": "1234"
}
###
GET http://20.89.131.34:443/api/v1/account
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MTY4NzczMiwiZXhwIjoxNjkxNjk2NzMyfQ.WrrAz7BOcSjIe550pQ0NFqic7BTC2d9tF71s7svDqWs

###
GET http://20.89.131.34:443/api/v1/account/list/?section=001
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MTY4Mzk3NywiZXhwIjoxNjkxNjkyOTc3fQ.DUtJVjBZXW43VRSCMxn5drIM1bMZvuLeYPhecu9hAjo

###
POST http://20.89.131.34:443/api/v1/account/revise/level
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MTY4NDkxNSwiZXhwIjoxNjkxNjkzOTE1fQ.DpDeNDLiFp6t1k1pH44BjGkj-7eHQpL_0bCO-Z5O0MA

{
    "username": "1234",
    "newLevel": 20
}
###
POST http://20.89.131.34:443/api/v1/account/revise/section
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikphc29uIiwiaWF0IjoxNjkxMjQ3NTEyLCJleHAiOjE2OTEyNTY1MTJ9.WDOy_45zpPCpO5YEEUiEM1_a3Lb8ETI5ajl1KTjLZEI

{
    "username": "jack",
    "newSection": "002"
}
###
POST http://20.89.131.34:443/api/v1/fish/data/?section=002
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MTY4NzczMiwiZXhwIjoxNjkxNjk2NzMyfQ.WrrAz7BOcSjIe550pQ0NFqic7BTC2d9tF71s7svDqWs

{
    "fishData": {
        "23": {"bc": 20, "err": 0,"active":1},
        "26": {"bc": 30, "err": 0,"active":0}
    }
}

###
GET http://20.89.131.34:443/api/v1/fish/table/?section=003&fishesID=3013,6006
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MTY4MDA2MCwiZXhwIjoxNjkxNjg5MDYwfQ.tB10ciKPIhbEoIMe95K4ATFVGeIDb1enk99JKHAh_tc


###
GET http://20.89.131.34/api/v1/fish/data/?section=001&fishesID=23,24
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY4OTY3NjMwNiwiZXhwIjoxNjg5Njg1MzA2fQ.XnkpiKaALzMbzuAhQsUFWXQTs8RsEX6sPv4PHMihdUI

###
GET http://20.89.131.34/api/v1/fish/history_data/?section=001&fishesID=23,24&versions=1,2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY4OTU5MDUwNiwiZXhwIjoxNjg5NTk5NTA2fQ.zQAxxAz6HHnXpNi1UVr2k3sOylDbravFiRc7nmRTT4s

###
POST http://20.89.131.34:443/api/v1/fish/control/?section=002
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikphc29uIiwiaWF0IjoxNjkxNjc4MzM3LCJleHAiOjE2OTE2ODczMzd9.ryvAFm9KE-pRzGGIVScQXlVjboS-Zjumt8hvSP_Ad8w

{
    "fishControl":{
        "led":{
            "23":{
                "led1": {"r":11,"g":21,"b":22,"a":40},
                "led2": {"r":20,"g":21,"b":22,"a":40}
            },
            "24":{
                "led1": {"r":21,"g":21,"b":22,"a":40},
                "led2": {"r":22,"g":21,"b":22,"a":40}
            }
        },
        "motion":{
            "id": "23",
            "motion": 2
        },
        "mode":{
            "id": "23,24",
            "mode": 0
        }
    }
}

###
POST http://20.89.131.34:443/api/v1/fish/delete/?section=002
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MTY4ODk0MiwiZXhwIjoxNjkxNjk3OTQyfQ.uW24nO2Yg1LUP_uTVsVMIShAMrrW_RfQEt1l48yghIU

{
    "fishesID": ["23","26"]
}
###
GET http://20.89.131.34:443/api/v1/video/?video_uid=0021
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MTIzODYwNiwiZXhwIjoxNjkxMjQ3NjA2fQ.PVHyF1IOOk03Pa4880rml6mRXMIUPUQJXCn7p4Bwrt0
