POST http://20.89.131.34/api/v1/account/sign_up
Content-Type: application/json

{
    "username": "123",
    "mail": "jack2563@gmail.com",
    "password": "735434cae08df8e591c1549da88c6d87",
    "section": "001"
}
###
POST http://20.89.131.34/api/v1/account/login
Content-Type: application/json

{
    "username": "john",
    "password": "735434cae08df8e591c1549da88c6d87"
}

###
POST http://20.89.131.34/api/v1/account/delete_user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMzQiLCJpYXQiOjE2OTI2MzEwNDcsImV4cCI6MTY5MjY0MDA0N30.VCkGbzr2EpwsLiNb2Xo62f2-QwwhHbsvmrpFfxC3GeI

###
POST http://20.89.131.34/api/v1/account/remove_user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MjYzMTM2NSwiZXhwIjoxNjkyNjQwMzY1fQ.MZC2aQu-2kPG7L9WR_5EaD6LW4CmVqQdA6fPeZSeFCY

{
    "username": "1234"
}
###
GET http://20.89.131.34/api/v1/account
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJpYXQiOjE2OTIxMTcxNjIsImV4cCI6MTY5MjEyNjE2Mn0.lR9EIpaNekfv1O2SSB2Zfgj_V5WFEcz_7tMnJMni22g

###
GET http://20.89.131.34/api/v1/account/list/?section=001
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MzA2MDkzOCwiZXhwIjoxNjkzMDY5OTM4fQ.eZXXhGAPGamBjQz7t5uwH9RJyF5B5s4WwrPEETnY7Pc

###
POST http://20.89.131.34/api/v1/account/revise/level/?section=002
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJpYXQiOjE2OTMwNjExNjMsImV4cCI6MTY5MzA3MDE2M30.E9uE0oVwP2REnXiuXWHq5NKrVYq53a64OFyRbtMCh1o

{
    "username": "djy",
    "newLevel": 20
}
###
POST http://20.89.131.34/api/v1/account/revise/section
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MTg3NTAyMiwiZXhwIjoxNjkxODg0MDIyfQ.GGj1_16bVlJ7KjGwU_CCGl_jr6v3JP5E9Vje1NKisIU

{
    "username": "jack",
    "newSection": "003"
}
###
POST http://20.89.131.34/api/v1/fish/data/?section=002
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MjYzMjA1MCwiZXhwIjoxNjkyNjQxMDUwfQ.yMh6zIYK7lMF9yA5euA82-G6BpAkP0caTw5UHEX6pcY

{
    "fishData": {
        "29": {"bc": 1, "err": 1,"active":2}
    }
}

###
GET http://20.89.131.34/api/v1/fish/table/?section=003&fishesID=6006
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MjYwNTYwMCwiZXhwIjoxNjkyNjE0NjAwfQ.kOIE-cBUX8F0FhEuT5dKQyGKlrrWiSOWEIzweV_jM1s


###
GET http://20.89.131.34/api/v1/fish/data/?section=002&fishesID=29
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MjYzMjA1MCwiZXhwIjoxNjkyNjQxMDUwfQ.yMh6zIYK7lMF9yA5euA82-G6BpAkP0caTw5UHEX6pcY

###
GET http://20.89.131.34/api/v1/fish/history_data/?section=003&fishesID=6006&versions=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJpYXQiOjE2OTIxMjEzMTcsImV4cCI6MTY5MjEzMDMxN30.6tndvUeiDspJZQFgTD1Pt-YvbkBEa8U3j-a6iaX6Uto

###
POST http://20.89.131.34/api/v1/fish/control/?section=002
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikphc29uIiwiaWF0IjoxNjkxNjc4MzM3LCJleHAiOjE2OTE2ODczMzd9.ryvAFm9KE-pRzGGIVScQXlVjboS-Zjumt8hvSP_Ad8w

{
    "fishControl":{
        "led":{
            "23":{
                "led1": {"r":11,"g":21,"b":22,"a":40},
                "led2": {"r":20,"g":21,"b":22,"a":40}
            },
            "24":{
                "led1": {"r":21,"g":21,"b":22,"a":40},
                "led2": {"r":22,"g":21,"b":22,"a":40}
            }
        },
        "motion":{
            "id": "23",
            "motion": 2
        },
        "mode":{
            "id": "23,24",
            "mode": 0
        }
    }
}

###
POST http://20.89.131.34/api/v1/fish/delete/?section=002
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MjYzMjA1MCwiZXhwIjoxNjkyNjQxMDUwfQ.yMh6zIYK7lMF9yA5euA82-G6BpAkP0caTw5UHEX6pcY

{
    "fishesID": ["29"]
}
###
GET http://20.89.131.34/api/v1/video/?video_uid=1&section=002
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MTkxMzc5MywiZXhwIjoxNjkxOTIyNzkzfQ.y2vpad0KlqtVWPELBdUGQ7eKYmaw0kY4BdprzMQV0LM

###
GET http://20.89.131.34/home
Cookie:token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MTc2ODczMCwiZXhwIjoxNjkxNzc3NzMwfQ.x-S_txC02B18EY56ZIBeGvZTrN7GmibB491IVhV9ym0