POST http://localhost/api1/login_respond/
Content-Type: application/json

{
    "account":"123",
    "password": "735434cae08df8e591c1549da88c6d87"
}

###
GET http://localhost/api1/account/init
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY4ODkwMjY5MiwiZXhwIjoxNjg4OTA0NDkyfQ.sLlfOoJ2EG8XgpP4cQnCeqpst3DpbpQ7oHiFcPEGaVw

###
GET http://localhost/api1/fish_table/24.25

###
POST http://localhost/api1/fish_data/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY4ODk3ODk5MCwiZXhwIjoxNjg4OTc5ODkwfQ.TLpE1kDaYWdioI8wkQY2Y-CF7ZshyIX542Z4hYN776s

{
    "fishData": {
        "23": {
            "time": 1662695926,
            "bc": 65,
            "err": 22,
            "active": 1
        }
    }
}
###
POST http://localhost/api1/fish_color/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY4ODk3OTA0MiwiZXhwIjoxNjg4OTc5OTQyfQ.kgb8M6X6QASqQ-Nyj2vhLnh2dPlajlFxlmHVncOR7Rw

{
    "fishColor": {
        "23": {
            "led1": {
                "r": 158,
                "g": 70, 
                "b": 28, 
                "w": 0
            }
        }
    }
}
###
GET http://localhost/api1/account/init
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY4ODk3OTA0MiwiZXhwIjoxNjg4OTc5OTQyfQ.kgb8M6X6QASqQ-Nyj2vhLnh2dPlajlFxlmHVncOR7Rw
