POST http://localhost/api1/login_respond/

{
    "acount":"123",
    "password": "615626626hunini"
}

###
GET http://localhost/api1/account/init
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY4ODg4ODgwNiwiZXhwIjoxNjg4ODkwNjA2fQ.QEkUgQYlbqxJVWa1p9CqekW3mFaYEgsb4uV2l2FZyWc
###
GET http://localhost/api1/fish_table/24.25

###
POST http://localhost/api1/fish_data/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY4ODg4ODgwNiwiZXhwIjoxNjg4ODkwNjA2fQ.QEkUgQYlbqxJVWa1p9CqekW3mFaYEgsb4uV2l2FZyWc

{
    "fishData": {
        "23": {
            "time": 1662695926,
            "bc": 65,
            "err": 22,
            "active": 1
        }
    }
}