POST http://20.89.131.34:443/api1/login_respond/
Content-Type: application/json

{
    "account": "123",
    "password": "735434cae08df8e591c1549da88c6d87"
}

### #messenge
GET http://20.89.131.34:443/api1/account/init 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY4ODk5MDY5NywiZXhwIjoxNjg4OTkxNTk3fQ.qai6AtzWY9XrPDNhu6ug7HGP0Jpe3AolcLHZlvV0eqs

###
POST http://20.89.131.34:443/api1/sign_up
Content-Type: application/json

{
    "account": "abc",
    "mail": "a@gmail.com",
    "password": "md5"
}

###
POST http://20.89.131.34:443/api1/login_respond/
Content-Type: application/json

{
    "account":"abc",
    "password": "md5"
}

###
GET http://20.89.131.34:443/api1/account/init
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFiYyIsImlhdCI6MTY4ODk5MTEzNywiZXhwIjoxNjg4OTkyMDM3fQ._TYRUskiMKUdUyz9eQyzeBAL8gHcDXXix9HjKlS3iKM
### #account/
POST http://20.89.131.34:443/api1/reviseLevel
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY4ODk4NzI3MiwiZXhwIjoxNjg4OTg4MTcyfQ.GZBwVOKwRRejmvROT1q6ot5eiOvBmt0ifkjfx2kjhA4

{
    "username": "abc",
    "newLevel": 3
}

###
POST http://20.89.131.34:443/api1/reviseLevel
Content-Type: application/json
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY4ODk5MDY5NywiZXhwIjoxNjg4OTkxNTk3fQ.qai6AtzWY9XrPDNhu6ug7HGP0Jpe3AolcLHZlvV0eqs

{
    "username": "abc",
    "newLevel": 1
}
