POST https://www.aifish.cc/api/v1/account/sign_up
Content-Type: application/json

{
    "username": "110310322",
    "mail": "ppp1244qqq@gmail.com",
    "password": "8cc22a1b4ea8657f44aec7e27317d0f7",
    "section": "001",
    "level": 10
}
###
GET https://www.aifish.cc/api/v1/account/verify/?username=110310322
Content-Type: application/json

###123:"735434cae08df8e591c1549da88c6d87" , 110310322:"dd79f98b3f8b63c94246beb7c75658a7" , lab314:"8cc22a1b4ea8657f44aec7e27317d0f7"
POST https://www.aifish.cc/api/v1/account/login
Content-Type: application/json

{
    "username": "123",
    "password": "735434cae08df8e591c1549da88c6d87"
}
###
POST https://www.aifish.cc/api/v1/fish/assign
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTcwMjE0MzExNiwiZXhwIjoxNzAyMTUyMTE2fQ.CP-ZfO3J1QgDwVXw7M4ekDj3r9KwXwO4CHREnts8Taw

{
    "username": "110310322",
    "fishUID": "0023001"
}

###
POST https://www.aifish.cc/api/v1/fish/disassign
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MzQxNTc1NCwiZXhwIjoxNjkzNDI0NzU0fQ.CTi99ThcxnfZ5MOcaFyjqA6fODQ5nsK-x2niEWzgRNg

{
    "username": "1234",
    "fishUID": "0023001"
}

###
POST https://www.aifish.cc/api/v1/account/delete_user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MzQxNTc1NCwiZXhwIjoxNjkzNDI0NzU0fQ.CTi99ThcxnfZ5MOcaFyjqA6fODQ5nsK-x2niEWzgRNg

###
POST https://www.aifish.cc/api/v1/account/remove_user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTcwMjE4NzUxMiwiZXhwIjoxNzAyMTk2NTEyfQ.IMps1ijl1NhzcoR9o4P-pge6pspP1Jzn4YAhnXX-sxA

{
    "username": "110310322"
}
###
GET https://www.aifish.cc/api/v1/account
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5NDEwMDUxNCwiZXhwIjoxNjk0MTA5NTE0fQ.KDnX_Gvr8Li2cDkBpFT8WtVPDm_895QWQDSV_Nmmrck

###
GET https://www.aifish.cc/api/v1/account/list/?section=001
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTcwMjE4NzUxMiwiZXhwIjoxNzAyMTk2NTEyfQ.IMps1ijl1NhzcoR9o4P-pge6pspP1Jzn4YAhnXX-sxA

###
POST https://www.aifish.cc/api/v1/account/revise/level
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTcwMjAzMjQwMSwiZXhwIjoxNzAyMDQxNDAxfQ.AiaM0ck8E29RUZBLMTINIkQQ0wWOdbYbSxYdmYdPDEE

{
    "username": "110310322",
    "newLevel": 10
}
###
POST https://www.aifish.cc/api/v1/account/revise/section
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTcwMjE4NzUxMiwiZXhwIjoxNzAyMTk2NTEyfQ.IMps1ijl1NhzcoR9o4P-pge6pspP1Jzn4YAhnXX-sxA

{
    "username": "110310322",
    "newSection": "001"
}

###
POST https://www.aifish.cc/api/v1/fish/?section=002001001
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTcwMTk3MzgyMywiZXhwIjoxNzAxOTgyODIzfQ.eOxGy_9nvKrdkhgR6qoDFWusf00RkB_J_XtbRkV8p9A

{
    "fishUID": "0023004"
}

###
POST https://www.aifish.cc/api/v1/fish/data/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTcwMTg2NzcyNywiZXhwIjoxNzAxODc2NzI3fQ.Vx5AekI3pxKmOl2u0Jksrtsvh_hq3r3y2ZQcLapo59M

{
    "fishData": {
        "0023001": {"bc": 0, "err": 0,"active":0, "version":"V1_7_3_LORA_TEST_CH10"},
        "0023002": {"bc": 0, "err": 0,"active":0, "version":"V1_7_3_LORA_TEST_CH10"},
        "0023004": {"bc": 0, "err": 0,"active":0, "version":"V1_7_3_LORA_TEST_CH10"},
        "0023006": {"bc": 0, "err": 0,"active":0, "version":"V1_7_3_LORA_TEST_CH10"},
        "0023009": {"bc": 0, "err": 0,"active":0, "version":"V1_7_3_LORA_TEST_CH10"},
        "0023010": {"bc": 0, "err": 0,"active":0, "version":"V1_7_3_LORA_TEST_CH10"},
        "0023011": {"bc": 0, "err": 0,"active":0, "version":"V1_7_3_LORA_TEST_CH10"},
        "0023012": {"bc": 0, "err": 0,"active":0, "version":"V1_7_3_LORA_TEST_CH10"},
        "0023013": {"bc": 0, "err": 0,"active":0, "version":"V1_7_3_LORA_TEST_CH10"},
        "0023019": {"bc": 0, "err": 0,"active":0, "version":"V1_7_3_LORA_TEST_CH10"}
    }
}

###
GET https://www.aifish.cc/api/v1/fish/table/?fishesUID=0023001
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhYjMxNCIsImlhdCI6MTcwMjExOTA4OCwiZXhwIjoxNzAyMTI4MDg4fQ.9BZH1ZLybrtBIVsG1MCPyB1Z5XdGzzMBBIhML9pTfKs


###
GET https://www.aifish.cc/api/v1/fish/data/?fishesUID=0023019
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjExMDMxMDMyMiIsImlhdCI6MTcwMjAzMjU1MSwiZXhwIjoxNzAyMDQxNTUxfQ.7RiM97XKvxaEzKWoUTTyjv6yaZW5Qrec5GXf1WWFmA4

###
GET https://www.aifish.cc/api/v1/fish/history_data/?fishesUID=0023001&versions=1697002072:1698064041
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5ODE2Mzg0OCwiZXhwIjoxNjk4MTcyODQ4fQ.853qp8OqQSXpjBHKySn0wZel__vonQVb8GtTdItDL8E

###
POST https://www.aifish.cc/api/v1/fish/control/?section=002001001
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTcwMDA1NTU1MSwiZXhwIjoxNzAwMDY0NTUxfQ.j08OLs09kAT7yzOiiod8rKLWorediGpLWuUdkfHXrxs

{
    "fishControl":{
        "led":{
            "3001":"K0",
            "3002":"K2"
        },
        "motion":{
            "id": "23",
            "motion": 2
        },
        "mode":{
            "id": "23,24",
            "mode": 0
        }
    }
}

###
POST https://www.aifish.cc/api/v1/fish/delete/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTcwMTg2ODM2NSwiZXhwIjoxNzAxODc3MzY1fQ.P9zq9iJg1oKJtE4xlVyzJ3v9nJ11hIXFMmiSeKFmfWU

{
    "fishesUID": ["3019"]
}
###
GET https://www.aifish.cc/api/v1/video/?video_uid=1&section=002
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MTkxMzc5MywiZXhwIjoxNjkxOTIyNzkzfQ.y2vpad0KlqtVWPELBdUGQ7eKYmaw0kY4BdprzMQV0LM

###
GET https://www.aifish.cc/home
Cookie:token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MTc2ODczMCwiZXhwIjoxNjkxNzc3NzMwfQ.x-S_txC02B18EY56ZIBeGvZTrN7GmibB491IVhV9ym0
###
POST https://www.aifish.cc/api/v1/instruction
Content-Type: application/json

{
    "instruction":{
        "code": "002",
        "name": "台北科大"
    }
}
###
POST https://www.aifish.cc/api/v1/depart
Content-Type: application/json

{
    "depart":{
        "code": "002001",
        "name": "先鋒大樓"
    },
    "instruction":{
        "code": "002"
    }
}
###
POST https://www.aifish.cc/api/v1/pool
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MzEzMDUzNCwiZXhwIjoxNjkzMTM5NTM0fQ.vlz8hjB7zM2kIaHweRTO5RnDWuxLzdwIdw9Wyj_i-w0

{   
    "instruction":{
        "code": "002"
    },
    "depart":{
        "code": "002001"
    },
    "pool":{
        "code": "002001001",
        "name": "CSL水池"
    }
}
###
POST https://www.aifish.cc/api/v1/fish/?section=002001001
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5Mjk1ODc0NSwiZXhwIjoxNjkyOTY3NzQ1fQ.j4zuDdyjJAVkhyejXS-TYSgNeJzY2M4mdFWxMBBbwCI

{
    "fish":{
        "uid": "002001"
    },
    "pool":{
        "id": "002001001"
    }
}

###

POST https://www.aifish.cc/api/v1/account/sticker
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5Mzc1NDk1NSwiZXhwIjoxNjkzNzYzOTU1fQ.k48udhky0SI6RR9pWmEhMYOR_Xb6a0t1a2bFOky_X5Y

###
GET https://www.aifish.cc/api/v1/account/sticker
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTcwMjEyMjkwNywiZXhwIjoxNzAyMTMxOTA3fQ.Sy44v_BOdxi4p4MM9df2MoRJKqLBJnr6_payQp4pIVc

###
GET https://www.aifish.cc/api/v1/fish/photosURL
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTcwMDAzMzM1NCwiZXhwIjoxNzAwMDQyMzU0fQ.I54Tk5py4Y_9Cu90fAHbmM0tscMg5bLrJRU1TwUm-sk

###
GET https://www.aifish.cc/api/v1/section
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5Mzc1NzA3MSwiZXhwIjoxNjkzNzY2MDcxfQ.P9hvLCl44m561H2rWqMN9z6rwxJ4aX6gZYv_kIB5bb0

###
POST https://www.aifish.cc/api/v1/fish/photo/change
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5ODE1MjU2MywiZXhwIjoxNjk4MTYxNTYzfQ.qwdd8_JDnm9r52joSG0xh-clTYixJBRp-Zc1VebReyw
Content-Type: application/json

{
    "fishUID": "0023001",
    "photoCode": 1
}
###
POST https://www.aifish.cc/api/v1/fish/relocal
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTcwMjI5NTEzOCwiZXhwIjoxNzAyMzA0MTM4fQ.nhzXDmMtrN8PTGOcS5LzxAwD_hKThRj_CghG238O_y0

{
    "fishUID": "0023001",
    "newPool": "002001001"
}
###
POST https://www.aifish.cc/api/v1/ota/burn
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTcwMTc1ODA2OCwiZXhwIjoxNzAxNzY3MDY4fQ.Nxqwsg1hKacnvLT7gxw_Bxul-waaKttLX6TmMds3Vq8

{
    "fishesUID": ["0023001","0023002"],
    "version": "test_2"
}

###
GET https://www.aifish.cc/api/v1/ota/bin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5Mzc1NDk1NSwiZXhwIjoxNjkzNzYzOTU1fQ.k48udhky0SI6RR9pWmEhMYOR_Xb6a0t1a2bFOky_X5Y

###
POST https://www.aifish.cc/api/v1/ota/bin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5Mzc1NDk1NSwiZXhwIjoxNjkzNzYzOTU1fQ.k48udhky0SI6RR9pWmEhMYOR_Xb6a0t1a2bFOky_X5Y

{
    "version": "v1.3.4test"
}
###
GET https://www.aifish.cc/api/v1/fish/photos/?fishUID=0023001
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTcwMjEyMDQ5NSwiZXhwIjoxNzAyMTI5NDk1fQ.orOP4SJ3M0o3vhlsmO-W6FLK3elBEF6KKOfbZd8AXTE

###
POST https://www.aifish.cc/api/v1/account/reset_password
Content-Type: application/json

{
    "username": "110310322",
    "mail": "ppp1244qqq@gmail.com",
    "password": "735434cae08df8e591c1549da88c6d87"
}
###
POST https://www.aifish.cc/api/v1/account/reset_password_check
Content-Type: application/json

{
    "username": "110310322",
    "code": "494934"
}
###
GET https://www.aifish.cc/
