POST http://20.89.131.34:443/api/v1/account/sign_up
Content-Type: application/json

{
    "username": "12345",
    "mail": "ppp1244qqq@gmail.com",
    "password": "735434cae08df8e591c1549da88c6d87",
    "section": "002001001"
}
###
GET http://20.89.131.34:443/api/v1/account/verify/?username=12345
Content-Type: application/json

###
POST http://20.89.131.34:443/api/v1/account/login
Content-Type: application/json

{
    "username": "1234",
    "password": "735434cae08df8e591c1549da88c6d87"
}
###
POST http://20.89.131.34:443/api/v1/fish/assign
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MzE1NDc1MywiZXhwIjoxNjkzMTYzNzUzfQ.KupkAhFOuv8_nK5yb7GsgSWf9FviNVlG4Mv01oUCRiY

{
    "username": "1234",
    "fishUID": "0023002"
}

###
POST http://20.89.131.34:443/api/v1/fish/disassign
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MzE0NzQ3MiwiZXhwIjoxNjkzMTU2NDcyfQ.pfVBhcVaCAsatX22zD-v_UDrIAiJVc3nG-vfu4PWC3w

{
    "username": "456",
    "fishUID": "0023002"
}

###
POST http://20.89.131.34:443/api/v1/account/delete_user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5Mjk2NzAxNywiZXhwIjoxNjkyOTc2MDE3fQ.U6gqW2zXS5rGo-XvSJBm6tkpIceEccVX0K3PGnnJjvs

###
POST http://20.89.131.34:443/api/v1/account/remove_user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5Mjk3NDg4NiwiZXhwIjoxNjkyOTgzODg2fQ.9VrRSBOUu5VTRzEL2ZQRxGJ1SrmSnw6rNs922MbMZRs

{
    "username": "abc"
}
###
GET http://20.89.131.34:443/api/v1/account
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MzE1NDc1MywiZXhwIjoxNjkzMTYzNzUzfQ.KupkAhFOuv8_nK5yb7GsgSWf9FviNVlG4Mv01oUCRiY

###
GET http://20.89.131.34:443/api/v1/account/list/?section=002
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MzE1NDc1MywiZXhwIjoxNjkzMTYzNzUzfQ.KupkAhFOuv8_nK5yb7GsgSWf9FviNVlG4Mv01oUCRiY

###
POST http://20.89.131.34:443/api/v1/account/revise/level
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMzQ1IiwiaWF0IjoxNjkyOTY3ODY5LCJleHAiOjE2OTI5NzY4Njl9.KfcSbU3UP6gGFhV9d6i_dp9S4eP-HDAnMS5L5d0wqM4

{
    "username": "1234",
    "newLevel": 10
}
###
POST http://20.89.131.34:443/api/v1/account/revise/section
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5Mjk2ODQ3OSwiZXhwIjoxNjkyOTc3NDc5fQ.75edsM-wJHNOLjJYDAAHi8D4diQWEb1VSDlNmeSHWsQ

{
    "username": "1234",
    "newSection": "002"
}
###
POST http://20.89.131.34:443/api/v1/fish/?section=002001002
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MzE1NDc1MywiZXhwIjoxNjkzMTYzNzUzfQ.KupkAhFOuv8_nK5yb7GsgSWf9FviNVlG4Mv01oUCRiY

{
    "fishUID": "0023004"
}

###
POST http://20.89.131.34:443/api/v1/fish/data/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MzE1NDc1MywiZXhwIjoxNjkzMTYzNzUzfQ.KupkAhFOuv8_nK5yb7GsgSWf9FviNVlG4Mv01oUCRiY

{
    "fishData": {
        "0023003": {"bc": 5, "err": 5,"active":1}
    }
}

###
GET http://20.89.131.34:443/api/v1/fish/table/?fishesUID=0023002,0023003,0023004
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MzE1NDc1MywiZXhwIjoxNjkzMTYzNzUzfQ.KupkAhFOuv8_nK5yb7GsgSWf9FviNVlG4Mv01oUCRiY


###
GET http://20.89.131.34:443/api/v1/fish/data/?fishesUID=0023003
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MzE1NDc1MywiZXhwIjoxNjkzMTYzNzUzfQ.KupkAhFOuv8_nK5yb7GsgSWf9FviNVlG4Mv01oUCRiY

###
GET http://20.89.131.34:443/api/v1/fish/history_data/?fishesUID=0023001,0023002&versions=1693063995:1693064041,1693064039:1693064040
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MzA3Mzg4OCwiZXhwIjoxNjkzMDgyODg4fQ.w1-8mkztLx7f5vne2Qro3Bbhk66ERrcwlvCtpVwUP_U

###
POST http://20.89.131.34:443/api/v1/fish/control/?section=002001001
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MzEyODA1MSwiZXhwIjoxNjkzMTM3MDUxfQ.8WUuPJ4fMQniLH4rdkFg6cWDyql2QlPxsWqjUQKbb9k

{
    "fishControl":{
        "led":{
            "23":{
                "led1": {"r":11,"g":21,"b":22,"a":40},
                "led2": {"r":20,"g":21,"b":22,"a":40}
            },
            "24":{
                "led1": {"r":21,"g":21,"b":22,"a":40},
                "led2": {"r":22,"g":21,"b":22,"a":40}
            }
        },
        "motion":{
            "id": "23",
            "motion": 2
        },
        "mode":{
            "id": "23,24",
            "mode": 0
        }
    }
}

###
POST http://20.89.131.34:443/api/v1/fish/delete/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MzA3Mzg4OCwiZXhwIjoxNjkzMDgyODg4fQ.w1-8mkztLx7f5vne2Qro3Bbhk66ERrcwlvCtpVwUP_U

{
    "fishesUID": ["0023003"]
}
###
GET http://20.89.131.34:443/api/v1/video/?video_uid=1&section=002
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MTkxMzc5MywiZXhwIjoxNjkxOTIyNzkzfQ.y2vpad0KlqtVWPELBdUGQ7eKYmaw0kY4BdprzMQV0LM

###
GET http://20.89.131.34:443/home
Cookie:token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MTc2ODczMCwiZXhwIjoxNjkxNzc3NzMwfQ.x-S_txC02B18EY56ZIBeGvZTrN7GmibB491IVhV9ym0
###
POST http://20.89.131.34:443/api/v1/instruction
Content-Type: application/json

{
    "instruction":{
        "code": "002",
        "name": "北科"
    }
}
###
POST http://20.89.131.34:443/api/v1/depart
Content-Type: application/json

{
    "depart":{
        "code": "001",
        "name": "部門1"
    },
    "instruction":{
        "code": "002"
    }
}
###
POST http://20.89.131.34:443/api/v1/pool
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5MzEzMDUzNCwiZXhwIjoxNjkzMTM5NTM0fQ.vlz8hjB7zM2kIaHweRTO5RnDWuxLzdwIdw9Wyj_i-w0

{   
    "instruction":{
        "code": "002"
    },
    "depart":{
        "code": "001"
    },
    "pool":{
        "code": "002",
        "name": "先鋒大樓前水池2"
    }
}
###
POST http://20.89.131.34:443/api/v1/fish/?section=002001001
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlhdCI6MTY5Mjk1ODc0NSwiZXhwIjoxNjkyOTY3NzQ1fQ.j4zuDdyjJAVkhyejXS-TYSgNeJzY2M4mdFWxMBBbwCI

{
    "fish":{
        "uid": "002001"
    },
    "pool":{
        "id": "002001001"
    }
}

###
